## Deliverable 2. Create a Customer Travel Destinations Map.

In [1]:
# Dependencies and Setup
import pandas as pd
import numpy as np
import requests
import gmaps
import json
# Import API key
from config import g_key

# Configure gmaps API key
gmaps.configure(api_key=g_key)

In [2]:
# 1. Import the WeatherPy_database.csv file. 
city_data_df = pd.read_csv("Weather_Database/WeatherPy_database.csv")
city_data_df.head()

,Unnamed: 0,Unnamed: 0.1,City,Country,Max Temp,% Humidity,% Cloudiness,Wind Speed,Lat,Lng
0,0,0,Oranjestad,AW,82.35,78,20,20.71,12.5240,-70.0270
1,1,1,Vostok,RU,63.50,35,78,7.40,46.4856,135.8833
2,2,2,Punta arenas,CL,44.71,61,75,13.80,-53.1500,-70.9167
3,3,3,Ushuaia,AR,47.86,49,75,17.27,-54.8000,-68.3000
4,4,4,Barrow,US,30.22,80,100,21.85,71.2906,-156.7887

In [3]:
# 2. Prompt the user to enter minimum and maximum temperature criteria 
maxTempinput = True
minTempinput = True
while maxTempinput:
        givenMax = input("Please enter the Maximun Tempature: ")
        
        try:
            maxTemp = int(givenMax)
            maxTempinput = False
        except:
            print("not an integar")
            
while minTempinput:
        givenMin = input("Please enter the Minimun Tempature: ")

        try:
            minTemp = int(givenMin)
            minTempinput = False
        except:
            print("not an integar")

Please enter the Maximun Tempature: 80
Please enter the Minimun Tempature: 40

In [4]:
# 3. Filter the city_data_df DataFrame using the input statements to create a new DataFrame using the loc method.
clean_df = city_data_df.loc[(city_data_df['Max Temp'] > minTemp) & (city_data_df['Max Temp'] <= maxTemp)]
clean_df.head(10)

,Unnamed: 0,Unnamed: 0.1,City,Country,Max Temp,% Humidity,% Cloudiness,Wind Speed,Lat,Lng
1,1,1,Vostok,RU,63.50,35,78,7.40,46.4856,135.8833
2,2,2,Punta arenas,CL,44.71,61,75,13.80,-53.1500,-70.9167
3,3,3,Ushuaia,AR,47.86,49,75,17.27,-54.8000,-68.3000
5,5,5,Ushuaia,AR,47.86,49,75,17.27,-54.8000,-68.3000
8,8,8,Provideniya,RU,42.91,75,0,11.18,64.3833,-173.3000
9,9,9,Hermanus,ZA,62.02,49,11,7.20,-34.4187,19.2345
11,11,11,Ponta do sol,CV,73.18,79,16,15.68,17.1994,-25.0919
12,12,12,Vaini,TO,75.96,79,45,7.43,-21.2000,-175.2000
13,13,13,Bredasdorp,ZA,54.66,61,3,3.98,-34.5322,20.0403
15,15,15,Nantucket,US,61.00,94,0,4.61,41.2835,-70.0995

In [5]:
# 4a. Determine if there are any empty rows.

In [6]:
# 4b. Drop any empty rows and create a new DataFrame that doesn’t have empty rows.

In [7]:
# 5a. Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = clean_df[["City", "Country", "Max Temp", "Lat", "Lng"]].copy()

# 5b. Create a new column "Hotel Name"
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

            City Country  Max Temp      Lat       Lng Hotel Name
1         Vostok      RU     63.50  46.4856  135.8833
2   Punta arenas      CL     44.71 -53.1500  -70.9167
3        Ushuaia      AR     47.86 -54.8000  -68.3000
5        Ushuaia      AR     47.86 -54.8000  -68.3000
8    Provideniya      RU     42.91  64.3833 -173.3000
9       Hermanus      ZA     62.02 -34.4187   19.2345
11  Ponta do sol      CV     73.18  17.1994  -25.0919
12         Vaini      TO     75.96 -21.2000 -175.2000
13    Bredasdorp      ZA     54.66 -34.5322   20.0403
15     Nantucket      US     61.00  41.2835  -70.0995

In [8]:
# 6a. Set parameters to search for hotels with 5000 meters.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

# 6b. Iterate through the hotel DataFrame.
for index in hotel_df.index:
    # 6c. Get latitude and longitude from DataFrame
    lat = hotel_df["Lat"][index]
    lng = hotel_df["Lng"][index]
    params["location"] = f"{lat},{lng}"
    # 6d. Set up the base URL for the Google Directions API to get JSON data.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # 6e. Make request and retrieve the JSON data from the search. 
    response = requests.get(base_url, params=params)
    hotel_data = response.json()
    # 6f. Get the first hotel from the results and store the name, if a hotel isn't found skip the city.
    try:
        hotel_df["Hotel Name"][index] = hotel_data["results"][1]["name"]
        print(f"Hotel found for index {index}")
    except: 
        print(f"No hotel found for index {index}")

No hotel found for index 1
No hotel found for index 2
No hotel found for index 3
No hotel found for index 5
No hotel found for index 8
No hotel found for index 9
No hotel found for index 11
No hotel found for index 12
No hotel found for index 13
No hotel found for index 15
No hotel found for index 16
No hotel found for index 17
No hotel found for index 18
No hotel found for index 19
No hotel found for index 20
No hotel found for index 21
No hotel found for index 22
No hotel found for index 23
No hotel found for index 24
No hotel found for index 25
No hotel found for index 26
No hotel found for index 27
No hotel found for index 29
No hotel found for index 30
No hotel found for index 33
No hotel found for index 34
No hotel found for index 35
No hotel found for index 36
No hotel found for index 37
No hotel found for index 38
No hotel found for index 39
No hotel found for index 40
No hotel found for index 41
No hotel found for index 42
No hotel found for index 43
No hotel found for index 44
No hotel found for index 45
No hotel found for index 46
No hotel found for index 47
No hotel found for index 48
No hotel found for index 49
No hotel found for index 50
No hotel found for index 52
No hotel found for index 53
No hotel found for index 54
No hotel found for index 55
No hotel found for index 56
No hotel found for index 57
No hotel found for index 60
No hotel found for index 61
No hotel found for index 62
No hotel found for index 65
No hotel found for index 66
No hotel found for index 67
No hotel found for index 68
No hotel found for index 69
No hotel found for index 71
No hotel found for index 75
No hotel found for index 76
No hotel found for index 77
No hotel found for index 78
No hotel found for index 79
No hotel found for index 80
No hotel found for index 81
No hotel found for index 82
No hotel found for index 83
No hotel found for index 84
No hotel found for index 85
No hotel found for index 86
No hotel found for index 87

KeyboardInterrupt:

In [9]:
# 7. Drop the rows where there is no Hotel Name.
hotel_df['Hotel Name'].replace('', np.nan, inplace=True)
hotel_df.dropna(subset=["Hotel Name"], inplace=True)
hotel_df.head()

Empty DataFrame
Columns: [City, Country, Max Temp, Lat, Lng, Hotel Name]
Index: []

In [10]:
# 8a. Create the output File (CSV)
hotel_df.to_csv("WeatherPy_vacation.csv")
# 8b. Export the City_Data into a csv

,Unnamed: 0,City,Country,Max Temp,Lat,Lng,Hotel Name
0,9,Hermanus,ZA,62.02,-34.4187,19.2345,Harbour House Hotel
1,11,Ponta do sol,CV,73.18,17.1994,-25.0919,Sintanton Trekking i
2,12,Vaini,TO,75.96,-21.2000,-175.2000,Tonga South Beach House
3,15,Nantucket,US,61.00,41.2835,-70.0995,Faraway Nantucket
4,16,Rikitea,PF,73.31,-23.1203,-134.9692,Pension Bianca & Benoit

In [11]:
# 9. Using the template add city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

# 10a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = hotel_df[["Lat", "Lng"]]

In [12]:
# 11a. Add a marker layer for each city to the map. 
fig = gmaps.figure()
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(marker_layer)
# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))